version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passroot
      POSTGRES_DB: db
    ports:
    - 5432:5432
    expose:
    - "5432"
    volumes:
    - /db:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pg_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sudo@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
    - 80:80
    restart: always

  bot:
    build: tg_bot/
    restart: always
    expose:
    - "5432"
